import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getAuth } from '@autospace/network/src/config/authOptions';
import { AppProviders } from '@autospace/ui/components/molecules/AppProviders';

import { Header } from '@autospace/ui/components/organisms/Header';
import './global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Autospace | manager',
  description: 'Generated by create next app',
};

const MENU_ITEMS = [
  { label: 'New garage', href: '/new-garage' },
  { label: 'Valets', href: 'valets' },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header type="manager" menuItems={MENU_ITEMS} user={session?.user} />
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
