import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ApolloProvider } from '@autospace/network/src/config/apollo';
import { SessionProvider } from '@autospace/ui/components/molecules/SessionProvider';
import { ToastContainer } from '@autospace/ui/components/molecules/Toast';

import { Header } from '@autospace/ui/components/organisms/Header';
import './global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Autospace | manager',
  description: 'Generated by create next app',
};

const MENU_ITEMS = [
  { label: 'New garage', href: '/new-garage' },
  { label: 'Valets', href: 'valets' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider>
          <ApolloProvider>
            <Header type="manager" menuItems={MENU_ITEMS} />
            {children}
            <ToastContainer />
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
