import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MenuItem } from '@autospace/util/types';
import { AppProviders } from '@autospace/ui/components/molecules/AppProviders';
import { Container } from '@autospace/ui/components/atoms/Container';
import { Header } from '@autospace/ui/components/organisms/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Autospace | Valet',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [
  { label: 'Garages', href: '/' },
  { label: 'Admins', href: '/manageAdmins' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-25`}>
        <AppProviders>
          <Header type="admin" menuItems={MENUITEMS} />
          <Container>{children}</Container>
        </AppProviders>
      </body>
    </html>
  );
}
